name: Gitbook Generation

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main

jobs:
  gitbook-generation:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        language: [en, ja, zh, pt-br, gl, es]

    steps:
    - uses: actions/checkout@v5

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.6'
        working-directory: 'book/scripts/'
        bundler-cache: true

    - name: Generate ToC
      run: |
        cd book/scripts/
        ruby generate_toc.rb ${{ matrix.language }} 
        echo "Generated book for: ${{ matrix.language }}" >> $GITHUB_STEP_SUMMARY

    - name: Commit updated toc.md for the book
      uses: stefanzweifel/git-auto-commit-action@v6
      with:
        commit_message: Writing updated toc.md for the ${{ matrix.language }} book
        branch: ${{ github.head_ref }}
