# from: https://github.com/marketplace/actions/link-checker
# link checker used is 'liche': https://github.com/raviqqe/liche

name: Link Check on Patterns and README

on:
  push:
    branches:
      - "main"
  pull_request:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 8 * * *'

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
    # - uses: actions/checkout@v2
    # - name: Link Checker
    #   id: lc
    #   uses: peter-evans/link-checker@v1
    #   with:
    #     args: -v -d . -x "http://creativecommons.org/licenses|https://isc-inviter.herokuapp.com|https://github.com/rcs/rcs-viewer/pull/81|fearlesschangepatterns.com|https://ulir.ul.ie/bitstream/handle/10344/4443/Stol_2014_inner.pdf|https://docs.github.com/en/rest/metrics/statistics|https://docs.github.com/en/rest/search#search-repositories" README.md patterns/ book/ translation/ -r
    # - name: Fail if there were link errors
    #   run: exit ${{ steps.lc.outputs.exit_code }}
      - uses: actions/checkout@v3

      - name: Restore lychee cache
        uses: actions/cache@v3
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.5.0
        with:
          args: --verbose --no-progress --cache --max-cache-age 1d README.md patterns/ book/ translation/
          fail: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}